### ISSUE TITLE
cqparts move

### ISSUE THREAD

**Issue by zignig** [justbuchanan/cadquery-models#1]
Looking to duplicate a build like this for @cqparts/experimental

**Comment by justbuchanan** [comment]
Cool, let me know what I can do to help. And feel free to copy whatever makes sense from this repo or the docker image in https://github.com/justbuchanan/docker-cadquery.

**Comment by zignig** [comment]
@justbuchanan , closing this one. the http://cqparts.github.io/ site is coming along.

Fork cqparts/experimental and add some objects in ... ;)
